# Generated by Django 4.2.14 on 2024-08-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titile',
            new_name='title',
        ),
    ]
